#!/usr/bin/env bash
set -euo pipefail

SCRIPT_DIR="$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" && pwd)"

echo
echo "========================================"
echo " Configuration setup"
echo "========================================"
echo

# echo "==> Configuring Micro..."

# mkdir -p ~/.config/micro

# cat > ~/.config/micro/settings.json <<'EOF'
# {
#     "colorscheme": "simple"
# }
# EOF

echo "==> Configuring Foot..."

FOOT_INI="$HOME/.config/foot/foot.ini"

mkdir -p "$(dirname "$FOOT_INI")"
install -m 644 "$SCRIPT_DIR/.config/foot/foot.ini" "$FOOT_INI"

echo "==> Configuring Helix..."

HELIX_CONFIG="$HOME/.config/helix/config.toml"

mkdir -p "$(dirname "$HELIX_CONFIG")"
install -m 644 "$SCRIPT_DIR/.config/helix/config.toml" "$HELIX_CONFIG"

echo "==> Configuring Bash..."

install -m 644 "$SCRIPT_DIR/.bashrc" "$HOME/.bashrc"

echo "==> Configuring Sway..."

AUTOSTART=~/.config/sway/config.d/autostart_applications
OUTPUT=~/.config/sway/config.d/output

if ! grep -Fqx 'exec fcitx5' "$AUTOSTART"; then
  cat >> "$AUTOSTART" <<'EOF'

# Fcitx5
exec fcitx5
EOF
fi

if ! grep -Fqx 'exec blueman-applet' "$AUTOSTART"; then
  cat >> "$AUTOSTART" <<'EOF'

# Blueman Applet
exec blueman-applet
EOF
fi

if ! grep -Fqx 'exec thunar --daemon' "$AUTOSTART"; then
  cat >> "$AUTOSTART" <<'EOF'

# Thunar daemon
# Keep Thunar running in the background so `thunar .` opens independently
# from the terminal that launched it.
exec thunar --daemon
EOF
fi

if ! grep -Fqx 'include ~/.config/sway/outputs' "$OUTPUT"; then
  cat >> "$OUTPUT" <<'EOF'

# Outputs generated by nwg-displays
include ~/.config/sway/outputs
EOF
fi

echo "==> Configuring services..."

sudo systemctl mask power-profiles-daemon.service
sudo systemctl enable auto-cpufreq.service
sudo systemctl enable bluetooth.service

echo
echo "========================================"
echo " Configuration completed!"
echo "========================================"
echo

echo "Manual GUI configuration:"
echo
cat <<'EOF'
  - Run fcitx5-configtool:
      Toggle Input Method: Alt + Left Shift
      Temporarily Toggle Input Method: Disabled
      Clipboard addon: Disabled

  - In auto-cpufreq:
      Turn Bluetooth on boot off
EOF

echo
echo "Log out and log back in to apply all changes."
echo
